// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkjmfpuaeabmoziyqiag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdram1mcHVhZWFibW96aXlxaWFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ1NzAyNzQsImV4cCI6MjA5MDE0NjI3NH0.e2DDlUbWgvmfWGC39Ts_lcq2O15zrsEvFvl9Q3Amwgk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});